### ISSUE TITLE
@Kenoshen todo list

### ISSUE THREAD

**Issue by Kenoshen** [bitDecayGames/LudumDare34#1]
- [x] finish animagic code refactor with normals
- [x] animagic UI work to make usable
- [ ] state machine interface
- [ ] example state machine for reference
- [ ] scene transitions and menu setup 
- [ ] thoughts on AI state machine
- [ ] fat jar

**Comment by Kenoshen** [comment]
Giving up on this...
